#![forbid(unsafe_code)]
#![warn(missing_docs)]

//! Rust code generation for the experimental Aegis IDL.

use aegis_protocol_idl::{
    fingerprint_hex, schema_fingerprint, Document, Field, FieldPresence, FieldType, Message,
};

/// Generates a Rust module from a parsed Aegis IDL document.
pub fn generate_rust_module(document: &Document) -> String {
    let mut out = String::new();
    out.push_str("// Generated by aegis-protocol-codegen.\n");
    out.push_str("// This file is experimental and may change before Aegis 1.0.\n\n");
    out.push_str("#![allow(dead_code)]\n\n");

    if let Some(package) = &document.package {
        out.push_str(&format!("pub const AEGIS_PACKAGE: &str = {:?};\n", package));
    }
    out.push_str(&format!(
        "pub const AEGIS_SCHEMA_FINGERPRINT_HEX: &str = {:?};\n\n",
        fingerprint_hex(schema_fingerprint(document))
    ));

    for capability in &document.capabilities {
        let const_name = sanitize_const_ident(&capability.name);
        out.push_str(&format!(
            "pub const CAPABILITY_{const_name}: &str = {:?};\n",
            capability.name
        ));
    }
    if !document.capabilities.is_empty() {
        out.push('\n');
    }

    for message in &document.messages {
        emit_message(&mut out, message);
        out.push('\n');
    }

    out
}

fn emit_message(out: &mut String, message: &Message) {
    let type_name = sanitize_type_ident(&message.name);
    let lifetime = if message_needs_lifetime(message) {
        "<'a>"
    } else {
        ""
    };
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str(&format!("pub struct {}{} {{\n", type_name, lifetime));
    for field in &message.fields {
        out.push_str(&format!(
            "    pub {}: {},\n",
            sanitize_field_ident(&field.name),
            rust_field_type(field)
        ));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("impl{} {}{} {{\n", lifetime, type_name, lifetime));
    out.push_str(&format!(
        "    pub const TYPE_ID: u32 = 0x{:x};\n",
        message.type_id
    ));
    if let Some(max_size) = message.max_size {
        out.push_str(&format!("    pub const MAX_SIZE: u32 = {};\n", max_size));
    }
    if let Some(value) = &message.contract.requires_capability {
        out.push_str(&format!(
            "    pub const REQUIRED_CAPABILITY: &str = {:?};\n",
            value
        ));
    }
    if let Some(value) = &message.contract.allowed_state {
        out.push_str(&format!(
            "    pub const ALLOWED_STATE: &str = {:?};\n",
            value
        ));
    }
    if let Some(value) = &message.contract.security {
        out.push_str(&format!(
            "    pub const SECURITY_PROFILE: &str = {:?};\n",
            value
        ));
    }
    if let Some(value) = &message.contract.idempotency {
        out.push_str(&format!("    pub const IDEMPOTENCY: &str = {:?};\n", value));
    }
    out.push_str("}\n\n");

    emit_field_constants(out, &type_name, message);
}

fn emit_field_constants(out: &mut String, type_name: &str, message: &Message) {
    let module_name = sanitize_module_ident(&format!("{}_fields", type_name));
    out.push_str(&format!("pub mod {module_name} {{\n"));
    for field in &message.fields {
        let field_const = sanitize_const_ident(&field.name);
        out.push_str(&format!(
            "    pub const {field_const}_ID: u32 = {};\n",
            field.id
        ));
        if let Some(max_len) = field.constraints.max_len {
            out.push_str(&format!(
                "    pub const {field_const}_MAX_LEN: u32 = {};\n",
                max_len
            ));
        }
        if let Some(size) = field.constraints.fixed_size {
            out.push_str(&format!(
                "    pub const {field_const}_SIZE: u32 = {};\n",
                size
            ));
        }
        if let Some(max_items) = field.constraints.max_items {
            out.push_str(&format!(
                "    pub const {field_const}_MAX_ITEMS: u32 = {};\n",
                max_items
            ));
        }
        if let Some(item_max) = field.constraints.item_max_len {
            out.push_str(&format!(
                "    pub const {field_const}_ITEM_MAX_LEN: u32 = {};\n",
                item_max
            ));
        }
        if !field.policies.is_empty() {
            out.push_str(&format!(
                "    pub const {field_const}_POLICIES: &[&str] = &{:?};\n",
                field.policies
            ));
        }
    }
    out.push_str("}\n");
}

fn message_needs_lifetime(message: &Message) -> bool {
    message.fields.iter().any(|field| {
        matches!(field.presence, FieldPresence::Repeated)
            || matches!(
                field.ty,
                FieldType::String | FieldType::Bytes | FieldType::Hash256 | FieldType::Signature
            )
    })
}

fn rust_field_type(field: &Field) -> String {
    let base = match &field.ty {
        FieldType::Bool => "bool".to_owned(),
        FieldType::U8 => "u8".to_owned(),
        FieldType::U16 => "u16".to_owned(),
        FieldType::U32 => "u32".to_owned(),
        FieldType::U64 => "u64".to_owned(),
        FieldType::U128 => "u128".to_owned(),
        FieldType::I8 => "i8".to_owned(),
        FieldType::I16 => "i16".to_owned(),
        FieldType::I32 => "i32".to_owned(),
        FieldType::I64 => "i64".to_owned(),
        FieldType::I128 => "i128".to_owned(),
        FieldType::F32 => "f32".to_owned(),
        FieldType::F64 => "f64".to_owned(),
        FieldType::Decimal128 | FieldType::Money => "[u8; 16]".to_owned(),
        FieldType::TimestampNs | FieldType::DurationNs => "i64".to_owned(),
        FieldType::Uuid128 => "[u8; 16]".to_owned(),
        FieldType::Hash256 => "&'a [u8; 32]".to_owned(),
        FieldType::Signature => "&'a [u8]".to_owned(),
        FieldType::IpAddr => "[u8; 16]".to_owned(),
        FieldType::GeoPoint => "(f64, f64)".to_owned(),
        FieldType::Bytes => "&'a [u8]".to_owned(),
        FieldType::String => "&'a str".to_owned(),
        FieldType::Custom(name) => sanitize_type_ident(name),
    };

    match field.presence {
        FieldPresence::Required => base,
        FieldPresence::Optional => format!("Option<{base}>"),
        FieldPresence::Repeated => format!("&'a [{base}]"),
    }
}

fn sanitize_type_ident(input: &str) -> String {
    let mut out = String::new();
    for (idx, ch) in input.chars().enumerate() {
        if (idx == 0 && (ch.is_ascii_alphabetic() || ch == '_'))
            || (idx > 0 && (ch.is_ascii_alphanumeric() || ch == '_'))
        {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        "GeneratedType".to_owned()
    } else {
        out
    }
}

fn sanitize_field_ident(input: &str) -> String {
    let ident = sanitize_type_ident(input);
    match ident.as_str() {
        "type" | "match" | "ref" | "self" | "crate" | "super" | "fn" | "struct" | "enum"
        | "mod" | "move" | "async" | "await" => format!("{ident}_"),
        _ => ident,
    }
}

fn sanitize_const_ident(input: &str) -> String {
    sanitize_field_ident(input).to_ascii_uppercase()
}

fn sanitize_module_ident(input: &str) -> String {
    sanitize_field_ident(input).to_ascii_lowercase()
}

#[cfg(test)]
mod tests {
    use super::*;
    use aegis_protocol_idl::{parse_document, validate_document};

    #[test]
    fn generates_struct() {
        let doc = parse_document(
            r#"
            package billing.v1;
            capability billing.capture_payment {
                scope merchant_id:u64;
                expires required;
            }
            state Authenticated {
                allow CapturePayment using billing.capture_payment;
            }
            message CapturePayment @type(0x2101) @max_size(1024) @requires_capability(billing.capture_payment) @allowed_state(Authenticated) {
                required u64 merchant_id = 1;
                optional string reference = 6 max 128 utf8;
            }
            "#,
        )
        .unwrap();
        validate_document(&doc).unwrap();
        let code = generate_rust_module(&doc);
        assert!(code.contains("pub struct CapturePayment<'a>"));
        assert!(code.contains("pub const TYPE_ID: u32 = 0x2101;"));
        assert!(code.contains("AEGIS_SCHEMA_FINGERPRINT_HEX"));
        assert!(code.contains("REQUIRED_CAPABILITY"));
    }
}
